export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"


export const RELIGION_REQUEST = "RELIGION_REQUEST"
export const RELIGION_SUCCESS = "RELIGION_SUCCESS"
export const RELIGION_FAILURE = "RELIGION_FAILURE"


export const FORGOTPASSWORD_REQUEST = "FORGOTPASSWORD_REQUEST"
export const FORGOTPASSWORD_SUCCESS = "FORGOTPASSWORD_SUCCESS"
export const FORGOTPASSWORD_FAILURE = "FORGOTPASSWORD_FAILURE"

export const COMMUNITIES_REQUEST = "COMMUNITIES_REQUEST"
export const COMMUNITIES_SUCCESS = "COMMUNITIES_SUCCESS"
export const COMMUNITIES_FAILURE = "COMMUNITIES_FAILURE"

export const PROFILE_REQUEST = "PROFILE_REQUEST"
export const PROFILE_SUCCESS = "PROFILE_SUCCESS"
export const PROFILE_FAILURE = "PROFILE_FAILURE"

export const PROFILE_POST_REQUEST = "PROFILE_POST_REQUEST"
export const PROFILE_POST_SUCCESS = "PROFILE_POST_SUCCESS"
export const PROFILE_POST_FAILURE = "PROFILE_POST_FAILURE"



export const PROFILE_USER_REQUEST = "PROFILE_USER_REQUEST"
export const PROFILE_USER_SUCCESS = "PROFILE_USER_SUCCESS"
export const PROFILE_USER_FAILURE = "PROFILE_USER_FAILURE"

export const PROFILE_IMAGE_USER_REQUEST = "PROFILE_IMAGE_USER_REQUEST"
export const PROFILE_IMAGE_USER_SUCCESS = "PROFILE_IMAGE_USER_SUCCESS"
export const PROFILE_IMAGE_USER_FAILURE = "PROFILE_IMAGE_USER_FAILURE"
